id: editor-exposure

info:
  name: Editor Configuration File - Detect
  author: DhiyaneshDk
  severity: low
  description: Editor configuration file was detected.
  metadata:
    max-request: 1
    verified: true
    shodan-query: html:"editorconfig"
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.editorconfig"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "= true"
          - "= space"
        condition: or

      - type: word
        part: header
        words:
          - "application/json"
          - "text/html"
        negative: true
        condition: or

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
