id: ftp-credentials-exposure

info:
  name: FTP Credentials Exposure
  author: pikpikcu
  severity: high
  description: FTP credentials were detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
    verified: true
    google-query: inurl:"/ftpsync.settings"
  tags: config,ftp,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/ftpsync.settings"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "FTPSync"
          - "overwrite_newer_prevention"
          - "default_folder_permissions"
        condition: and

      - type: status
        status:
          - 200
