id: parameters-config

info:
  name: Parameters.yml - File Discovery
  author: DhiyaneshDK
  severity: high
  description: Parameters.yml was discovered.
  reference: https://www.exploit-db.com/ghdb/5986
  metadata:
    max-request: 4
    verified: true
    shodan-query: html:"parameters.yml"
  tags: exposure,cloud,devops

http:
  - method: GET
    path:
      - "{{BaseURL}}/parameters.yml"
      - "{{BaseURL}}/app/config/parameters.yml"
      - "{{BaseURL}}/parameters.yml.dist"
      - "{{BaseURL}}/app/config/parameters.yml.dist"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'parameters:'
          - 'database_user'
          - 'database_password'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by mp on 2022/07/15
