id: webpack-config

info:
  name: Webpack Configuration File - Detect
  author: ambassify
  severity: info
  description: Webpack configuration file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    max-request: 1
    shodan-query: html:"webpack.config.js"
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/webpack.config.js"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "module.exports"
          - "const"
        condition: or

      - type: word
        part: header
        words:
          - "application/javascript"
          - "text/javascript"
        condition: or

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/24
