id: api-appveyor

info:
  name: AppVeyor API Test
  author: dwisiswant0
  severity: info
  reference:
    - https://www.appveyor.com/docs/api/
  tags: token-spray,appveyor
  metadata:
    max-request: 1

self-contained: true
http:
  - method: GET
    path:
      - "https://ci.appveyor.com/api/roles"
    headers:
      Content-Type: application/json
      Authorization: Bearer {{token}}

    matchers:
      - type: word
        part: body
        words:
          - '"roleId":'
          - '"created":'
        condition: and